---
- hosts: test-servers
  become: true
  tasks:
    - name: update apt list
      apt:
        update_cache: yes    
    - name: Install Apache
      apt: name=apache2 update_cache=yes state=latest
    
    - name: create an empty folder
      file:
        path: /root/demo_new
        state: directory
         
    - name: remove an existing folder
      file:
        path: /root/testfolder
        state: absent    
  
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

